### ISSUE TITLE
Eliminating the need for manually select the device?

### ISSUE THREAD

**Issue by yoninezer** [ksvc/KSYAirStreamer_iOS#2]
(Translated to english) 

> The use of KSYAirStreamer screencast, eliminating the need for users to manually select the device, because we already know the name of the device, you can take the initiative to select the corresponding device

Can you please elaborate, how exactly do I automatically connect to a device without prompting the user to manually select the device name ? Thanks.

**Comment by pengbins** [comment]
Do you translate this from this article http://www.jianshu.com/p/a100901ff544 ? 

If you want find out how it works, here is a reference.
https://spin.atomicobject.com/2012/04/23/ios-mirroring-and-programmatic-airplay-selection/

and you can find more examples on github.

The main idea is using private API, to simulate user's manual selection.

Due to private API change, automatically connect only works on iOS before iOS11 (not included).

**Comment by yoninezer** [comment]
@pengbins  Thanks!
